import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "@/app/components/Layouts/LayoutWrapper";

export const metadata: Metadata = {
  title: "Admin Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#F5F5F6]">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
